name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: prepare deploy
        run: mkdir -p /tmp/npm-global && npm config set prefix /tmp/npm-global && export PATH=$PATH:/tmp/npm-global/bin
      - name: install firebase-tools
        run: npm install -g firebase-tools
      - name: deploy to firebase
        run: /tmp/npm-global/bin/firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" -only hosting
