name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: prepare deploy
        run: mkdir -p /root/.npm-global && npm config set prefix /root/.npm-global && export PATH=$PATH:/root/.npm-global/bin && npm install -g firebase-tools
      - name: deploy to firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" -only hosting
