name: firebsae deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: prepare deploy
        run: mkdir ~/.npm-global && npm config set prefix '~/.npm-global' && export PATH=~/.npm-global/bin:$PATH && source ~/.profile && npm install -g firebase-tools
      - name: deploy to firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" -only hosting
